apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Backstage.v1alpha1.rhdh.redhat.com
    argocd.argoproj.io/sync-wave: "1"
  name: rhdh-operator
  namespace: rhdh-operator
spec:
  targetNamespaces: []
 