---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: developer-hub
    openshift.io/cluster-monitoring: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: developer-hub
spec: {}
---
apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: developer-hub
  namespace: developer-hub
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
    extraFiles:
      mountPath: /opt/app-root/src
    replicas: 2
    route:
      enabled: true
  database:
    enableLocalDb: true