apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.componentName }}
  title: ${{ values.componentTitle }}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
    {%- if values.giteaProjectID %}
    gitea/project-id: "${{ values.giteaProjectID }}"
    gitea/instance: ${{ scm }}}
    {%- endif %}
spec:
  type: ${{ values.applicationType }}
  lifecycle: development
  owner: ${{values.owner | dump}}
