apiVersion: pfe.rhpds.com/v1
kind: Gitea
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: gitea
  namespace: gitea
spec:
  giteaSsl: true
  giteaVolumeSize: 4Gi
  postgresqlVolumeSize: 4Gi
